name: capsa
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python
  - sphinx
  - sphinx_rtd_theme
  - furo
  - sphinx-tabs
  - sphinx-material
  - numpy
  - tensorflow-gpu
  - pip
  # pip dependencies
  - pip:
    - tensorflow-probability
    - matplotlib