name: build_workflow

on:

  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        required: false
        default: 'ubuntu-18.04'
      py_version:
        description: 'Python version'
        required: true
        default: '3.9'

  workflow_call:
    inputs:
      os:
        description: 'Operating system'
        required: false
        type: string
        default: 'ubuntu-18.04'
      py_version:
        description: 'Python version'
        required: true
        type: string

jobs:

  build_job:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '${{ inputs.py_version }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt
          pip install -e .

      - name: Build the dist package
        run: python setup.py clean --all sdist

      - name: Install the package
        run: pip install dist/capsa*

      - name: Test it
        run: |
          cd ./test
          python -m unittest test_ensemble.py -b
          python -m unittest test_mve.py -b

      - name: Dockerize
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/capsa
          tag_with_sha: true
          build-args: PY_VERSION='${{ inputs.py_version }}'
